## Repaso Matrices - Taller 3

Este taller debe ser entregado a más tardar el viernes 3 de noviembre a medianoche (11:59pm).

In [313]:
#Samuel Murillo Herrera - Alejandra María Yanza Gaviria
import numpy as np

### 1. Multiplicación de matrices

**[20 pts]** Construya el algoritmo de multiplicación de matrices y encuentre el resultado de las siguientes operaciones.

a.

 <img src ='./img/matrix1.png' width=200px>

 b.
 
  <img src ='./img/matrix2.png' width=200px>

  c. 

  <img src ='./img/matrix3.png' width=200px>

  **[10 pts]** Utilizando dos matrices cuadradas, demuestre que la multiplicación no es conmutativa.

In [314]:
A1=np.array([[5,-4,-2],
             [5,-5,4],
             [2,5,-4],
             [-5,4,3],
             [3,-4,-3]])
B1=np.array([5,-2,-3])

A2=np.array([[0,-1,-1,3],
             [5,-5,-2,2],
             [1,0,4,5]])
B2=np.array([[0,-3],
             [-2,-1],
             [3,-3]])

A3=np.array([[2,-5,5,1],
             [5,2,-7,-6],
             [-6,-1,7,-4],
             [5,4,1,-5]])
B3=np.array([[0,4,-7,1,-6],
             [-1,-6,-5,1,1],
             [2,-1,-6,5,-5],
             [-3,-6,6,3,5]])

In [315]:
def MatrixMultiplication (A,B):
    mxn=np.shape(A)
    nxp=np.shape(B)
    
    if len(nxp)==1:
        C=np.zeros((mxn[0]))
        for i in range(0,mxn[0]):
            C[i]=np.dot(A[i,:],B)
    
    elif len(mxn)==1:
        C=np.zeros((mxn[0]))
        for i in range(0,mxn[0]):
            C[i]=np.dot(A,B[:,i])

    elif mxn[1]==nxp[0]:
        C=np.zeros((mxn[0],nxp[1]))
        for i in range(0,mxn[0]):
            for j in range(0,nxp[1]):
                C[i,j]=np.dot(A[i,:],B[:,j])

    else:
        return "Dimensiones incorrectas"
    return C

In [316]:
MatrixMultiplication(A1,B1)


array([ 39.,  23.,  12., -42.,  32.])

In [317]:
MatrixMultiplication(A2,B2)

'Dimensiones incorrectas'

In [318]:
MatrixMultiplication(A3,B3)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

Para dos matrices cuadradas de puede que ver que no se cumple AB=BA

In [319]:
A=np.array([[2,-5,5,1],
             [5,2,-7,-6],
             [-6,-1,7,-4],
             [5,4,1,-5]])
B=np.array([[1,2,3,1],
             [1,2,3,-6],
             [1,2,3,-4],
             [5,4,1,-5]])

In [320]:
MatrixMultiplication(A,B)

array([[  7.,   8.,   7.,   7.],
       [-30., -24.,  -6.,  51.],
       [-20., -16.,  -4.,  -8.],
       [-15.,   0.,  25.,   2.]])

In [321]:
MatrixMultiplication(B,A)

array([[ -1.,   0.,  13., -28.],
       [-36., -28.,   6.,   7.],
       [-26., -20.,   8.,  -3.],
       [ -1., -38.,  -1.,   2.]])

En efecto, la multiplicación de matrices no es conmutativa

### 2. Reducción gaussiana
**[40 pts]** Utilizando el algoritmo de reducción Gaussiana, resuelva los siguientes sistemas de ecuaciones:

a.

 <img src ='./img/gaussian1.png' width=300px align=center>

 b.

 <img src ='./img/gaussian2.png' width=300px>

In [322]:
A1=np.array([[3,1,-1],
             [1,-2,1],
             [4,-1,1]])
b1=np.array([2,0,3])

A2=np.array([[1,1,1],
             [0,-8,10],
             [4,-8,0]])
b2=np.array([0,0,6])

In [323]:
def gaussian_elimination(A: np.array,b: np.array):
    n = np.shape(A)[0]
    M = np.zeros(shape=(n,n+1))
    M[:,0:n] = A
    M[:,n] = b
    for i in range (1,n):
        for j in range(0,i):
            C=(M[i,j]/M[j,j])
            M[i,:]=M[i,:]-C*M[j,:]
    return M

def gaussian_Complete_elimination (M: np.array):
    n=np.shape(M)[0]
    Sol=np.zeros([n])
    for i in range (0,n):
        s=M[n-i-1,n]/M[n-i-1,n-i-1]
        for j in range (0,n):
            s-=M[n-i-1,n-j-1]*Sol[j]/M[n-i-1,n-i-1]
        Sol[i]=s
    return Sol[::-1]

In [324]:
def linalg_solve (A:np.array,b:np.array):
    return gaussian_Complete_elimination(gaussian_elimination(A,b))

In [325]:
linalg_solve(A1,b1)

array([0.71428571, 0.85714286, 1.        ])

In [326]:
linalg_solve(A2,b2)

array([ 0.71052632, -0.39473684, -0.31578947])

### 3. Valores y vectores propios

**[30 pts]** Un sistema de tres osciladores acoplados, tiene las siguientes ecuaciones de movimiento:

<img src='./img/eqmotion.png' width=200>

Al reemplazar $x_1=c_1e^{i\omega t},x_2=c_2e^{i\omega t},x_3=c_3e^{i\omega t}$ se obtienen las siguientes ecuaciones algebraicas

<img src='./img/algeq.png'  width=200>

Para encontrar las frecuencias, se puede pensar lo anterior como un problema de valor propio regido por la ecuación

$M\vec{v} = -\omega^2 \vec{v}$

donde $\vec{v}$ es el vector de amplitudes $c_1,c_2,c_3$ y $-\omega^2$ los valores propios. Utilizando el método de la potencia, encuentre la frecuencia máxima y mínima de oscilación del sistema y sus amplitudes asociadas para cada caso (modo normal). En su solución pruebe $k_{11}=k_{22}=k_{33}=-2\kappa, k_{12}=k_{21}=k_{23}=k_{32}=\kappa, k_{13}=k_{31}=0$.




In [327]:
k=1
m1=1
m2=1
m3=1
H1=np.array([[-2*k/m1,k/m1,0/m1],
             [k/m2,-2*k/m2,k/m2],
             [0/m3,k/m3,-2*k/m3]])
Z=np.array([1,1,1])

In [328]:
def Metodo_potencia (A,Z,k):
    for i in range(0,k):
        Z=Z/(np.sqrt(np.matmul(Z.T,Z)))
        Z=np.matmul(A,Z)
    W=Z/(np.sqrt(np.matmul(Z.T,Z)))   
    Vpropio=np.matmul(W.T,np.matmul(A,W))
    return Vpropio,W

In [329]:
P1=Metodo_potencia(H1,Z,30)
ValorPropioMax=P1[0]
VectorPropioMax=P1[1]
P2=Metodo_potencia(np.linalg.inv(H1),Z,20)
ValorPropioMin=(P2[0])**-1
VectorPropioMin=P2[1]

In [330]:
print(ValorPropioMax,VectorPropioMax,ValorPropioMin,VectorPropioMin)

-3.414213562373095 [ 0.5        -0.70710678  0.5       ] -0.585786437626905 [0.5        0.70710678 0.5       ]
